### ISSUE TITLE
potential bug with N-bit set to 1

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/qpack#51]
@marten-seemann It turns out, the issue was actually due to the setting of `N` bit at [Literal Field Line with Name Reference](https://www.rfc-editor.org/rfc/rfc9204.html#name-literal-field-line-with-nam)

When I encode that packet I set the `N` bit to 1, to ensure that literal string representation is sent across the subsequent hops by the intermediary.  

[RFC Reference](https://www.rfc-editor.org/rfc/rfc9204.html#section-4.5.4-3)

The condition `buf[0]&0x20 > 0` [here](https://github.com/quic-go/qpack/blob/9160514575d0ad5457d01ef82d59f3f464fe2963/decoder.go#L199) is triggering the `errNoDynamicTable` error. But in this case the `N` bit does not have anything to do with Dynamic table unless you have a reason.

I flipped the 'N' bit to 0 and that solved the issue. PR Reference for the QPACK that I use: [PR](https://github.com/kixelated/web-transport-rs/pull/41)

_Originally posted by @DineshAdhi in https://github.com/quic-go/qpack/issues/33#issuecomment-2325782295_

**Comment by kixcord** [comment]
Yeah, I was hard-coding `N=1` because I didn't care if a later intermediary converted the entry from literal to dynamic. I switched it to `N=0` to unbreak quic-go but the correct fix is to remove that linked check. 

Note that web-transport-quinn doesn't support a dynamic table either.

**Comment by marten-seemann** [comment]
@kixcord I'm wondering if there'd be value in submitting QIF files to https://github.com/qpackers/qifs, so all implementations could run their interop test against an encoding that uses `N=1`. What do you think?

**Comment by kixcord** [comment]
> https://github.com/qpackers/qifs

I didn't know that existed. Up to you.
